[profile.default]
src = "src"
out = "out"
# https://book.getfoundry.sh/projects/soldeer
libs = ["dependencies"]

[dependencies]
"@openzeppelin-contracts" = { version = "5.0.2" }
"@prb-math" = { version = "4.0.3" }
forge-std = { version = "1.8.1" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
